---
name: Publish Documentation

on:
  push:
    branches: ["main"]

permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  build:
    runs-on: ubuntu-latest
    # Skip job if actor is github-actions[bot] to ensure agent safety
    if: ${{ github.actor != 'github-actions[bot]' }}
    steps:
      - uses: actions/checkout@v4
      
      - name: Try to download artifact from build workflow
        id: download-artifact
        uses: dawidd6/action-download-artifact@v6
        with:
          workflow: build.yml
          workflow_conclusion: success
          name: documentation-site
          path: site
          check_artifacts: true
          search_artifacts: true
          if_no_artifact_found: warn
        continue-on-error: true
      
      - name: Set up Python
        if: steps.download-artifact.outcome != 'success'
        uses: actions/setup-python@v3
        with:
          python-version: "3.13"
      
      - name: Install dependencies
        if: steps.download-artifact.outcome != 'success'
        run: |
          python -m pip install --upgrade pip
          if [ -f pyproject.toml ]; then pip install -e ".[dev]"; fi
          if [ -f dev-requirements.txt ]; then pip install -r dev-requirements.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Build MkDocs site
        if: steps.download-artifact.outcome != 'success'
        run: |
          mkdocs build
      
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: site/
  
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
